[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tinysoundfont"
dynamic = ["version"]
description = "Python bindings for loading Sound Fonts (sf2 format) and generating audio samples"
readme = "README.md"
license = "MIT"
requires-python = ">=3.7"
authors = [
    { name = "Nathan Whitehead", email = "nwhitehe@gmail.com" },
]
dependencies = [
    "pybind11~=2.6.1",
    "setuptools>=42",
    "wheel",
]

[tool.hatch.version]
path = "src/__version__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/test",
]

[tool.hatch.build.targets.wheel]
packages = [ "src" ]
