name: Doc

on: [push, pull_request]

jobs:
    build_doc:
        name: Build docs
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5

            - name: Install dev requirements
              run: apt install python3-pyaudio

            - name: Install doc requirements
              run: python -m pip install -r doc/requirements.txt

            - name: Local install of module
              run: python -m pip install .

            - name: Build docs
              run: cd doc && make html
